[supervisord]
nodaemon=true

[program:X11]
command=/usr/bin/Xvfb :0 -screen 0 1024x768x24
user=root
autorestart=true

[program:x11vnc]
command=/usr/bin/x11vnc
user=root
autorestart=true

[program:fluxbox]
command=/usr/bin/startfluxbox
user=root
autorestart=true

[program:iqfeed-startup]
command=/root/iqfeed_startup.sh
user=root
autorestart=true
environment=WINEARCH="win64",WINEPREFIX="/root/.wine64",DISPLAY=":0",WINEDEBUG="-all"
startretries=999
startsecs=5

[program:iqfeed-proxy]
command=nodejs /root/app/proxy.js
user=root
autorestart=true
startretries=999

[program:iqfeed-keepalive]
command=/root/iqfeed_keepalive.sh
user=root
autorestart=true
startretries=999
startsecs=10
